### ISSUE TITLE
Allow item ordering

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/angular-extension-registry#9]
Perhaps add a weight field on items & let the directive do a simple filter by weight before rendering.

**Comment by jawnsy** [comment]
This would be a really good enhancement, especially for OpenShift Online. At present, if we add a link to the User menu, it always appears at the bottom, but given that the User menu already has a "Log out" link, it ends up looking funny:

![screenshot from 2017-01-03 15-21-11](https://cloud.githubusercontent.com/assets/52710/21626837/715173ce-d1c8-11e6-8858-bf48c81efaa3.png)

Maybe it's just me, but I'd always expect "Log out" or "About" to be at the bottom of the help & user menus.  cc @abhgupta @damemi @jwforres @ajacobs21e

**Comment by benjaminapetersen** [comment]
The tricky thing about this is assigning a meaningful "weight" property.  Initially we proposed a way to get at the underlying array by providing a function to rearrange items as desired, but this creates a potential for one extension to clobber another.

**Comment by jawnsy** [comment]
Yeah, I understand the challenge there. I'm curious what Eclipse does with their extension points, it seems this plugin is modelled after that mechanism a little :wink: If we don't do _something_ though, then I'm afraid the user-nav extension point is essentially unusable (since Log out will always appear at top).

Since this is just for Online, I'm open to even hacking around with the DOM in a fragile way, for now, while we think about a better solution.

**Comment by benjaminapetersen** [comment]
Great Q.  Eclipse was referenced when we first built this out, though I personally have never used it's extension point system.

If we added arbitrary weights (10,20,30) to items for sorting it would be easy enough to be able to swap in new items in the gaps (11, etc).

**Comment by ajacobs21e** [comment]
@jawnsy I think it is reasonable to make Log out the default bottom option

**Comment by jwforres** [comment]
Yeah I agree from a UX perspective, we would have some technical issues to
work through to make that possible.
